[package]
name = "digimatic"
version = "2.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
axum = { version = "0.8.9", features = ["ws"] }
chrono = "0.4.43"
csv = "1.4.0"
eframe = "0.29"
egui_plot = "0.29"
hex = "0.4.3"
rand = "0.10.1"
rand_distr = "0.6.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serialport = "4.8.1"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tower-http = { version = "0.7.0", features = ["fs"] }
